### ISSUE TITLE
Unable to use send to upload scanner.

### ISSUE THREAD

**Issue by rudrasingh99** [modzero/mod0BurpUploadScanner#22]
Hy,

I'm Unable to use send to upload scanner options. Whenever I click on it nothing happens , sometimes it does many times it doesn't

Let me know.

**Comment by floyd-fuh** [comment]
Hi, please let me know what the Error tab in the Extender tab says when you click on the upload scanner extension.

**Comment by floyd-fuh** [comment]
Feel free to reopen this issue with more details from the Extender tab.
