### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by van7hu** [modzero/mod0BurpUploadScanner#30]
```
Traceback (most recent call last):
  File "/home/xml/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 804, in processHttpMessage
    body = FloydsHelpers.jb2ps(base_request_response.getResponse())[iResponseInfo.getBodyOffset():]
  File "/home/xml/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4085, in jb2ps
    return ''.join(map(lambda x: chr(x % 256), arr))
OutOfMemoryError: java.lang.OutOfMemoryError: GC overhead limit exceeded

```

**Comment by floyd-fuh** [comment]
This is not the extension's fault. You should give your Burp more memory.

**Comment by floyd-fuh** [comment]
You are running and old version of this extension. Please update.

Yes, I will take care that this is not automatically submitted as a bug in the future.

This is a bug in your configuration. See Burp's troubleshooting page: https://support.portswigger.net/customer/portal/articles/1965913-troubleshooting point "9. Burp runs out of memory". Basically running Burp like you did will make Burp behave non-deterministic as random parts of Burp will fail to allocate memory, making the very foundation of a software fail.

Or in other words: you computer's RAM is not sufficiently allocated to the Java process that is Burp. You have to change the argument to the -Xmx command line option.
