### ISSUE TITLE
Option to set static collaborator URL

### ISSUE THREAD

**Issue by austinjdean** [modzero/mod0BurpUploadScanner#38]
We are currently testing an application that resides behind a client VPN. From behind their VPN, we are unable to poll our private collaborator instance. If we were able to set a static collaborator URL, we could deploy a collaborator client on a box that is able to poll our instance, and listen there once the scan starts. Is there currently a way to do this? Googling for such a feature didn't turn up much.

**Comment by floyd-fuh** [comment]
Hi Austin. Your question is unrelated to the UploadScanner extension (this git repository). However, I'll explain it for you anyway:

Burp uses a collaborator server instance. If you would like to read a little bit more about it, it is described here:

https://portswigger.net/burp/documentation/collaborator

That page also points you to the Project Options - Misc tab where you can configure which Burp Collaborator should be used for you Burp client:

https://portswigger.net/burp/documentation/desktop/options/misc-project#burp-collaborator-server

It also points you to the documentation how you can setup a private Burp Collaborator server. For example behind your VPN:

https://portswigger.net/burp/documentation/collaborator/deploying

Mind though that you will need a wildcard TLS certificate. Alternatively you will have to use a IP-based Collaborator, which can cause trouble. However, I tried to support IP-based Collaborators in this extension. I would still recommend to set up your own wildcard TLS Burp Collaborator server.
