### ISSUE TITLE
Feature Request: Improve Audit Strategy

### ISSUE THREAD

**Issue by luh2** [modzero/mod0BurpUploadScanner#44]
Hi,

Currently, when a scan is started, it will use the default audit strategy in Burp 2.0 which has everything in it, not just the extension generated requests. It would be nice if it uses a default audit strategy that only scans for extension generated issues.

**Comment by floyd-fuh** [comment]
Unsure if I get you right. What you describe is when you start a scan manually via the UploadScanner GUI? So you don't want the "Do Active Scan" module checkbox to be checked by default?

**Comment by luh2** [comment]
No. In Burp 1.x one could disable all checks besides extensions in the Scanner tab. In Burp 2.x you select the Audit Policy (equivalent more or less to the scanner configuration back then) when you create a new audit. When you just hit "scan", it will use the default policy. The default policy will do more than just extensions.

**Comment by luh2** [comment]
That's one way of dealing with it, that slipped my mind. Thanks.
