### ISSUE TITLE
Any way to configure ReDownloader a bit more flexible?

### ISSUE THREAD

**Issue by HD421** [modzero/mod0BurpUploadScanner#5]
Hello! First of all thank you for this great extension. I apprechiate this huge amount of work you've done.
Today I faced a trivial problem: I need to download uploaded file, but upload link contains Hash instead of ${FILENAME}, I see this hash in response after succesfull uploading. Unfortunately, I still didn't know all the features of the module, there is any way to fix this problem without touching the code? Thank you!

**Comment by floyd-fuh** [comment]
Good to hear you like the extension.

Why not use the ReDownloader parser? Have you checked out the tutorial videos for it? It can use a hash from the upload response as part of the redownload URL.

**Comment by floyd-fuh** [comment]
As this should be trivial to do with how it is explained in the tutorial video on https://www.modzero.ch/share/uploadscanner/UploadScanner_105_ReDownloader.mp4 I close this issue for now. If you have any further questions, feel free to ask
