### ISSUE TITLE
Infinite horizontal scrolling - Burp v2020.1

### ISSUE THREAD

**Issue by HannahLaw-Portswigger** [modzero/mod0BurpUploadScanner#60]
We’ve just released a new version of Burp that has some big changes to the HTTP message editor.

Notably, a scroll pane is now implemented inside the message editor.

Unfortunately, this has caused an infinite scrolling issue with your extension. This was reported to us by a user of your BApp, who provided a video of the issue (https://monosnap.com/file/Gqw1tXkXKupRRSAsBSEN3rcjbAYyDw).

If possible, could you remove the scroll pane instance you have implemented, and create a pull request against the PortSwigger branch of your repository so that we can review the changes and update the BApp?

**Comment by mattymcfatty** [comment]
ditto

**Comment by mattymcfatty** [comment]
hey @HannahLaw-Portswigger is this change documented anywhere? I tried poking around to change the code myself but wasn't sure what to replace the references to JScrollPane with. I couldn't find references to scroll functions in burp extender online anywhere. Could you help point me in the right direction?

**Comment by HannahLaw-Portswigger** [comment]
Removing the instance of JScrollPane in line 714 seems to fix the infinite scrolling issue. After that, it would be a matter of sorting out the UI again so that it looks nice (I would guess restricting the initial size of the message editor).

I don't have any documentation to provide you with, unfortunately.

https://github.com/modzero/mod0BurpUploadScanner/blob/a7ba73189cd65433446c517f5c633d02eeff213f/UploadScanner.py#L714

**Comment by HannahLaw-Portswigger** [comment]
This issue should be resolved in the next release of Burp.

**Comment by putsi** [comment]
This issue seems to still be present on UploadScanner that is loaded from BApp store and installed in Burp v2020.2.1.
I tried the fix provided by @HannahLaw-Portswigger but it completely removed the whole right pane.

**Comment by HannahLaw-Portswigger** [comment]
This issue was fixed shortly after the release of 2020.2.1, so it was unable to be included in that release. We have not yet released 2020.3 (but it shouldn't be too far off).

**Comment by putsi** [comment]
Ok, do you know if there is a hotfix that I can apply? I tried removing the line 714 but it completely removes the panel.

**Comment by HannahLaw-Portswigger** [comment]
You could replace the scroll pane instance with a panel of some type. However, we have fixed the root cause of the issue, which will be in the next release.

**Comment by bluecanarybe** [comment]
@HannahLaw-Portswigger 

I've been waiting for this, thanks!

**Comment by HannahLaw-Portswigger** [comment]
We're pleased to announce the release of Burp v2020.4

**Comment by putsi** [comment]
Can confirm that the vulnerability is now fixed on Burp v2020.4.
